services:
  - type: web
    name: personal-safety-risk-analyzer
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 3 --bind 0.0.0.0:$PORT
    healthCheckPath: /